version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - exhaustruct_v5
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - lll
    - mnd
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gosmopolitan:
      allow-time-local: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
